### ISSUE TITLE
Unable to connec the bot 

### ISSUE THREAD

**Issue by arahmy** [TFAGaming/DiscordJS-V14-ModMail-Bot#15]
Hello, 
Im trying to setup the bot on my vps, i have completed all config files but i have this error when i start the bot : 

`Unable to connect to the bot, this might be an invalid token or missing required intents!
 Error: Used disallowed intents
    at WebSocketShard.onClose (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\@discordjs\ws\dist\index.js:1132:18)
    at connection.onclose (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\@discordjs\ws\dist\index.js:676:17)
    at callListener (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onClose (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\ws\lib\event-target.js:220:9)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emitClose (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\ws\lib\websocket.js:260:10)
    at TLSSocket.socketOnClose (C:\Users\ipolo\Desktop\DiscordJS-V14-ModMail-Bot-8.0.0\node_modules\ws\lib\websocket.js:1272:15)
    at TLSSocket.emit (node:events:526:35)
    at node:net:323:12
    at TCP.done (node:_tls_wrap:588:7)`

Can you help please ?

**Comment by mrkingtj** [comment]
Have you set the indents on the discord dev portal? (where you made the bot and got the token from)

**Comment by arahmy** [comment]
No I don’t, I will try this tomorrow and comment again to inform you about that, thanks
