### ISSUE TITLE
Error upon starting

### ISSUE THREAD

**Issue by ghost** [TFAGaming/DiscordJS-V14-ModMail-Bot#5]
Promise {
  <rejected> TypeError: isJSONEncodable is not a function
      at C:\Users\Crack\Downloads\DiscordJS-V14-ModMail-Bot-main\node_modules\discord.js\src\structures\MessagePayload.js:137:59
      at Array.map (<anonymous>)
      at MessagePayload.resolveBody (C:\Users\Crack\Downloads\DiscordJS-V14-ModMail-Bot-main\node_modules\discord.js\src\structures\MessagePayload.js:137:49)
      at DMChannel.send (C:\Users\Crack\Downloads\DiscordJS-V14-ModMail-Bot-main\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:169:32)
      at Message.reply (C:\Users\Crack\Downloads\DiscordJS-V14-ModMail-Bot-main\node_modules\discord.js\src\structures\Message.js:803:25)
      at Client.<anonymous> (C:\Users\Crack\Downloads\DiscordJS-V14-ModMail-Bot-main\index.js:711:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      
      what does this man and hiw to rfix pls

**Comment by TFAGaming** [comment]
This is coming from discord.js folder. I'm not sure if this error is coming up because the version v14.6.0 of discord.js is out of support. The v7.0.0 (this project) is coming soon and it has a lot of bug fixes and features.
